internal/gateway/auth/token.go

A bug has been introduced by removing the audience from the JWT. Cluster login is not possible with the current state.

Reintroduce audience into jwts to fix cluster login

---

internal/gateway/usecases/get_auth_token.go

The k8s auth token was using the username which is able to change and then does not match clusterrolebindings and rolebindings in target clusters anymore.

Fix username in k8s auth token

---

CHANGELOG.md
pkg/eventsourcing/messaging/bus_rabbitmq.go
pkg/eventsourcing/messaging/bus_rabbitmq_config.go

Currently it is not possible to change the exchange name that is used
for publishing messages. It is always set to the value `m8_events`. This
is inconvenient for other projects that want to take advantage of the
message bus implementation.
I considered adding a new parameter to the `NewRabbitEventBusConfig` function
but that would potentially break other implementations. On the other hand I
couldn't think of a good reason why the fields of the config struct should actually
be private. Only the `url` has some logic bound to it, because the TLS settings
have conditionally to be reconfigured. For that reason I added a setter `SetURL`.

Make RabbitEventBusConfig fields accessible

---

pkg/eventsourcing/eventhandler/store_refresh_middleware.go

It has been observed that events are replayed even though they have been observed already.
So here’s the problem: The refresh middleware uses the timestamp of the last received event to query all events later than that. This is kind of bullshit and I will explain why:
* Even though an Event with a certain timestamp has been received, there could be a second event with the exact same timestamp that has been gone missing. So querying all events later than that won’t rescue you.
* Timestamps are in general something that are error prone because we all know time is something funny which can hit you pretty hard in the face.
It would be better to have a global event counter. Due to the nature of distributed systems we do not have something like that because this would need some kind of …

store_refresh_middleware seems to be buggy

---

pkg/eventsourcing/event_data.go
pkg/eventsourcing/event_data_test.go

When an event, despite having the same type, can have different payloads, it would helpful to wrap the [anypb.UnmarshalNew](https://pkg.go.dev/google.golang.org/protobuf/types/known/anypb#UnmarshalNew) function in order to offload the message resolution to `anypb`

Resolve message type when unmarshaling EventData

---

CHANGELOG.md

This has slipped through somewhere. Actually we do not need that since we already have detailed release information on the release page of the project.

Remove changelog in favor of releases page

---

.github/workflows/draft-release.yml
.github/workflows/golang.yaml
build/package/helm/gateway/files/policies/policies.rego
go.mk

Currently cluster login is impossible due to the strict policies and even the version command fails with permission denied.

Adjust allowed paths to all users for cluster login

---

build/package/helm/monoskope/Chart.yaml

Signed-off-by: Christian Hüning <christian.huening@finleap.com>
* update RabbitMQ Chart to 8.32.2
work towards #161

update rabbitmq chart to the latest available 8.x.x chart version

---

.github/workflows/golang.yaml
go.mk

Fix go coverage

---

pkg/domain/queryhandler.go
pkg/domain/repositories/tenant_user_repo.go
pkg/domain/repositories/tenant_user_repo_test.go

When a tenant has been deleted, the users of this tenant can still be queried as if the tenant would still exist. This fixes this by skipping deleted tenant on the server side.

Ignore deleted tenants on tenant users

---

pkg/domain/constants/events/events.go
pkg/domain/projectors/cluster.go

In previous changes the cluster bootstrap token has been removed, but due to the nature of event sourcing the events are still in the history. Therefore it is not a viable solution to remove the handling of those events. Readded a dummy handler again.

Make ClusterBootstrapTokenCreated known again

---

pkg/domain/aggregates/cluster.go

The removal of the handler for ClusterBootstrapTokenCreated breaks handling if the EventStore has events of that type for historical reasons. The handler is readded.

Readd handler for former events

---

internal/audit_log_test.go
internal/queryhandler/audit_log_server.go
internal/testenv.go
pkg/audit/formatters/audit/audit_formatter.go
pkg/audit/formatters/snapshotter.go
pkg/audit/formatters/user_snapshotter.go
pkg/domain/constants/formatters/formatters.go
pkg/domain/formatters/events/certificate.go
pkg/domain/formatters/events/cluster.go
pkg/domain/formatters/events/tenant.go
pkg/domain/formatters/events/user.go
pkg/domain/formatters/overviews/user.go

when getting the audit log of the users-overview the roles a user has and the tenants/clusters they belong to are missing from the output.
**AC:**
- the mentioned keys should have the “expected” values
- find out how they escaped the tests and fix

Fix roles/tenants/clusters values are missing from the audit log users overview

---

internal/integration_test.go
pkg/domain/aggregates/user_role_binding.go

as the title describes if a role binding was created once and deleted a new one with the same state can't be created again.

Fix user role binding can't be recreated after deletion

---

.gitignore
build/package/helm/monoskope/Chart.lock
build/package/helm/monoskope/Chart.yaml
build/package/helm/monoskope/templates/_helpers.tpl
build/package/helm/monoskope/templates/ambassador/ambassador-cert.yaml
build/package/helm/monoskope/templates/ambassador/ambassador-host.yaml
build/package/helm/monoskope/templates/ambassador/mappings/commandhandler.yaml
build/package/helm/monoskope/templates/ambassador/mappings/gateway.yaml
build/package/helm/monoskope/templates/ambassador/mappings/queryhandler.yaml
build/package/helm/monoskope/templates/ambassador/mappings/scimserver.yaml
build/package/helm/monoskope/values.yaml

This change is mainly required for the newer Emissary-Ingress Helm chart, which deploys RBAC resources in v1.

WIP: Use most recent Ambassador / Emissary-Ingress

---

build/package/helm/monoskope/values.yaml

- enable deployment of default listener
- added workaround for the host mapping problem, when the port send by GRPC (e.g. from a K8s service) does not match the port in the listener.

Fix issues with recent Emissary-Ingress version

---

build/package/helm/monoskope/templates/gateway/cert-auth.yaml
docs/operation/04-k8s-auth.md

An unexpected cert/private-key rotation by cert-manager might cause K8s auth to fail by leading to a state with new/old tokens and KubeAPIServers using the old/new pub key.

Change tls cert rotation policy to never and rotation docs

---

build/package/helm/queryhandler/templates/deployment.yaml

The newly introduced k8s authz feature breaks the start of the queryhandler if not configured because it tries to mount a secret which isn’t there.

Fix QueryHandler doesn't start when K8sAuthz is not configured

---

pkg/eventsourcing/messaging/bus_rabbitmq.go

In some use cases, it is beneficial if the queue that a worker consumes from is made durable. In that way, the queue and the messages would survive a restart of the RabbitMQ server.

Make worker queues durable

---

build/package/helm/commandhandler/templates/hpa.yaml
build/package/helm/eventstore/templates/cronjob-backup.yaml
build/package/helm/eventstore/templates/hpa.yaml
build/package/helm/gateway/templates/hpa.yaml
build/package/helm/monoskope/Chart.yaml
build/package/helm/queryhandler/templates/hpa.yaml
build/package/helm/scimserver/templates/hpa.yaml

Added support for Kubernetes +v1.25
**Changes**
- Added Helm Capabilities check of API versions available for:
- HorizontalPodAutoscaler
- CronJob
**Warning**: 
- CockroachDB helm chart version is also updated to v9.1.0, see chart changes [here](https://artifacthub.io/packages/helm/cockroachdb/cockroachdb/9.1.0?modal=template&template=cronjob-ca-certSelfSigner.yaml&compare-to=7.0.1). Default values comparison [here](https://artifacthub.io/packages/helm/cockroachdb/cockroachdb/9.1.0?modal=values&compare-to=7.0.1)
- CockroachDB version is still pinned to the same version as before

Feat/support k8s 1.25
